# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0002_remove_graphs_script_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graphs',
            new_name='Graph',
        ),
    ]
